### ISSUE TITLE
[Enhancement]: Transcription/Subtitle support

### ISSUE THREAD

**Issue by mfcar** [advplyr/audiobookshelf#2919]
### Describe the feature/enhancement

Transcription/Subtitle support
=== 

### Summary

Add initial support for transcriptions. Apple now supports transcriptions in podcasts. 

Some audiobook files have transcriptions, and currently, we can use tools based on [Whisper](https://github.com/openai/whisper) to transcribe audio to text. 

In fact, most software based on Whisper support transcribing audio to text and exporting it as an [SRT](https://en.wikipedia.org/wiki/SubRip) or [VTT](https://en.wikipedia.org/wiki/WebVTT) file. VTT is a native format for the web, and SRT is a common format for subtitles.

I'm creating this issue to discuss the best way to implement transcription support on the web player. I'm trying to implement some features on the pull request #

### Podcast transcription is supported by:

- [ ] https://podcasting2.org/podcast-namespace/tags/transcript

### Possible tasks:
 - [ ] Implement support for parsing and displaying VTT files. [WebVTT](https://developer.mozilla.org/en-US/docs/Web/API/WebVTT_API) #2918
 - [ ] Implement support for parsing and displaying SRT files (convert to vtt or try to parse directly?).
 - [ ] Support `<podcast:transcript>` tag in RSS feed. [Apple Docs](https://help.apple.com/itc/podcasts_connect/#/itcb54353390) / [Podcast Namespace](https://github.com/Podcastindex-org/podcast-namespace)
 - [ ] Handle CORS issues when fetching transcription files from external sources. [Podcasting 2.0 CORS](https://github.com/Podcastindex-org/podcast-namespace/blob/main/podcasting2.0.md#cors)
 - [ ] Implement logic to read transcription from a file with the same name as the audio file. #2918 
 - [ ] Define priority if both VTT and SRT files exist with the same name?
 - [ ] When a podcast has a transcription tag, automatically download the transcription and store it in the file system (offline mode).
 - [ ] Add a visual indication in the UI that a podcast/audiobook has a transcription available?
 - [ ] Implement a feature to search within the transcription (better if using a lateral panel)?
 - [ ] Implement a feature to highlight the current line of the transcription as the podcast/audiobook plays. #2918 
 - [ ] Implement a feature to navigate to a specific part of the podcast/audiobook by clicking on the transcription text. Seek to the corresponding time in the audio. #2918 
 - [ ] Implement a feature to toggle the display of the transcription on/off on the web player. #2918 
 - [ ] Implement a button to download the transcription file? Can be useful for editing or sharing. #2918 
 - [ ] Allows to upload a VTT file for transcription?

> Note: I think we need define a standard for multi-language transcriptions. For example use some prefix in the file name like `en-` for English and `es-` for Spanish.

### UI Ideas on the Web Player:

What's the best way to display the transcription on the web player?

 - [ ] Above/Below audio player controls. #2918 
   - Good: because the audio player is omnipresent on all pages and the transcription can be displayed in a fixed position. 
   - Bad: Not enough space to display multiple lines of text.
  
<img width="989" alt="Screenshot 2024-05-04 at 20 47 33" src="https://github.com/advplyr/audiobookshelf/assets/814828/4ba864bb-c2cf-4ef3-8bc6-5affadc3d52d">

---

 - [ ] Modal.
   - Good: More space to display multiple lines of text. Can float over the UI.
   - Bad: The modal can be intrusive.
- [ ] Lateral Panel. (like the iTunes/Apple Music).
  - Good: More space to display multiple lines of text. Can have a search feature. Better for implement the seek feature (click on the line and seek to the corresponding time).
  - Bad: Take up space on the screen. Not good for small screens.

<img width="1219" alt="Screenshot 2024-05-02 at 09 09 47" src="https://github.com/advplyr/audiobookshelf/assets/814828/f1e8320d-ae6c-4ce8-bb39-1c37c05aa0ab">

### Related
 - #1723

**Comment by sorena100** [comment]
Any updates? if not I might try to pick it up.

**Comment by Vito0912** [comment]
It currently makes not so much sense the start working on it (at least with the VUE side and react is still in active development). Please see README

I made a fork with both subtitle generation (to webvtt, also supporting karaoke style) and webvtt and shared some impressions in Discord:
https://discord.com/channels/942908292873723984/942913544272367706/1484286697096089690
But due to the fact that it a) was mainly AI written for personal use (although still a lot manual code and rewrites) and b) that see README no frontend features were ever merged (mainly b though)

**Comment by michalisb** [comment]
I am working on transcription, trying to think of best way to display it. TTML format might be the best way to provide information for karaoke or apple podcast/ audible style display.

A div can be used for a "paragraph", p for a sentence and the discreet words added in a span element.

**Comment by Vito0912** [comment]
Before you start working and if you plan to do an PR, please read the README. Not that you "waste" your time.

~~As for karaoke style I have a outdated fork and an active client that uses webvtt. It is natively supported by most softwares, even just with basic functionalities then. Maybe as an idea.~~ NVM, wrote it above here already

**Comment by michalisb** [comment]
Yeah, no worries. I am still working on the transcription part - and I have a VVT export/embed solution ready. But I really like the Apple Podcasts transcription view. No problems in having multiple subtitle tracks in M4B..
